### ISSUE TITLE
Does Samsung dex not work?

### ISSUE THREAD

**Issue by foxlesbiao** [klabit87/android_kernel_samsung_sdm845#1]
Does Samsung dex not work?

**Comment by klabit87** [comment]
Dex does work. Why wouldn't it?

**Comment by foxlesbiao** [comment]
Sorry, it's my mistake, it can be run after reinstalling

**Comment by klabit87** [comment]
> Sorry, it's my mistake, it can be run after reinstalling

Thanks for confirming.
