### ISSUE TITLE
i need help porting your kernel in postmarket os

### ISSUE THREAD

**Issue by madodream89** [klabit87/android_kernel_samsung_sdm845#3]
hi i am trying porting postmarket os in my samsung galaxy note 9 n9600 i want use your kernel but the shiity woke community of postmarket os not help me i need use your kernel in my port of postmarket os

0x0.st/s/ebuueplAF4kdQozAslW2rw/H8jU.txt

**Comment by madodream89** [comment]
https://gitlab.com/madodream89/samsung-galaxy-note-9-n9600-sdm845-postmarketos-port#modal-upload-blob

**Comment by madodream89** [comment]
not find the reposity for kernel

**Comment by klabit87** [comment]
Unfortunately, I can not help you on this.
