### ISSUE TITLE
gsi kernel does not work with Ubuntu touch gsi 

### ISSUE THREAD

**Issue by gutofroes132** [klabit87/android_kernel_samsung_sdm845#6]
The Ubuntu touch gsi + kernel gsi combination does not start the system, a layman's question, but Wie might be able to solve it, should I download the source and make the modifications described by ubports?

**Comment by klabit87** [comment]
I never claimed this source to be compatible with halium.  
You can use this source https://github.com/klabit/halium_starqlte

or the official droidian kernel source
https://github.com/droidian-devices/linux-android-samsung-starqlte

**Comment by gutofroes132** [comment]
I apologize for my lack of practice with github and ending up generating this unnecessary question, and I am extremely grateful for the help given to me on what path to follow.

**Comment by klabit87** [comment]
It’s a valid question. Good luck with Ubuntu touch

**Comment by gutofroes132** [comment]
One last question, (I don't know any other way to resolve any doubts with you, forgive me) can I use your kernel link ( https://github.com/klabit/halium_starqlte), without any modifications on a Galaxy Note 9?

**Comment by klabit87** [comment]
I linked you the wrong repo that’s my bad.
https://github.com/klabit/android_kernel_samsung_sdm845-1/tree/halium-10

use this kernel source. you should only need to compare the changes in defconfig and generate a defconfig for the note 9. Everything else in the source should be ready to go. 
Of course, the official droidian kernel source is the same situation iirc. 

The other repo I linked you I used to build the halium environment I think.

**Comment by gutofroes132** [comment]
immensely grateful to you, I've been trying for years to find a way to use a smartphone without Android, it will be my salvation

**Comment by madodream89** [comment]
so

> immensely grateful to you, I've been trying for years to find a way to use a smartphone without Android, it will be my salvation

now works ubuntu in note 9
